### ISSUE TITLE
Q: How to write and contribute documentation?

### ISSUE THREAD

**Issue by zehnm** [YIO-Remote/documentation#1]
Are there any plans or guidelines about the documentation format?

- Individual MD files?
- GitHub Wiki pages?

  E.g. something like https://github.com/xoseperez/espurna/wiki

- Other format?

I'm asking because I started documenting the development setup, buildroot process and everything I come across I'm working on. So far I put all notes in OneNote and then transfer it to MD.
My personal preference are wiki pages but I'm open to other formats, as long as it's not Sharepoint ;-)

**Comment by martonborzak** [comment]
We started using MD files, but open for suggestions regarding documentation. The idea was that we have this repo where we gather and organise all the docs, so it's not scattered all around.

**Comment by zehnm** [comment]
That makes total sense!
Have a look at the [GitHub wiki feature](https://help.github.com/en/articles/about-wikis). Default format is also MD, but allows for other formats. It makes it much easier to organize and find content.
The feature can be enabled in the repo settings.

**Comment by martonborzak** [comment]
Great! That's cool. I've enabled the wifi feature. Would you be able to start setting that up and creating your doc there? 
After we have to move all the other stuff too!

**Comment by zehnm** [comment]
Ok, I will start this week and set something up for an initial review.

**Comment by martonborzak** [comment]
Sounds good. Thanks!

**Comment by zehnm** [comment]
I have copied all MD files including their Git history into the [wiki](https://github.com/YIO-Remote/documentation/wiki):
- The wiki can be edited online or checked out and edited offline:

        git clone https://github.com/YIO-Remote/documentation.wiki.git

- The readme file is used as wiki home (Home.md).
  Unfortunately I lost the Git history for this file during rename. Sorry about that.
- Created an initial simple sidebar (_Sidebar.md).

@martonborzak & @carp3-noctem you have been adding documentation so far: please review if that's the way to go forward.
 
Next steps IF all agree:

1. Remove MD files in https://github.com/YIO-Remote/documentation
1. Slim down README in documentation and reference wiki for the detailed documentation
1. Continue documentation in wiki (I haven't added my dev setup doc yet)
1. Standardize naming, organize side bar

**Comment by martonborzak** [comment]
Sound like a plan. Thanks for moving it over!

**Comment by carp3-noctem** [comment]
I'm fine with it. Didn't know the feature yet. Will read through the documentation about git wiki and further on use this.

**Comment by martonborzak** [comment]
Removed the MD files, closing the issues. Feel free to expand on the README.
